# Generated by Django 3.2.25 on 2024-09-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
