# Generated by Django 3.2.25 on 2024-09-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240923_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Detaildescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
