# Generated by Django 3.2.25 on 2024-09-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_detaildescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Detaildescription',
            new_name='specification',
        ),
    ]
