# Generated by Django 3.2.25 on 2024-09-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
