# Generated by Django 3.2.25 on 2024-09-25 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_rating_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('customer', 'product')},
        ),
    ]
