# Generated by Django 3.2.25 on 2024-09-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20240926_0159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
